### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by BarbarosaQWE** [MoonFox2006/ESP01_Relay#1]
Здравствуйте, можете подсказать в чём проблема?
Установил VSCode и PlatformIO но прошивка не загружается через них
в проекте ничего не менял
![image](https://user-images.githubusercontent.com/106037113/169717544-4e54906e-b576-47a3-a803-643261970b17.png)

**Comment by MoonFox2006** [comment]
Перекачайте архив, в новых версиях компилятора и фреймворка старый код не собирался.
